apiVersion: v1
kind: Service
metadata:
  name: prakash-back-service
spec:
  type: NodePort
  selector:
    app: prakash-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082

