apiVersion: v1
kind: Service
metadata:
  name: prakash-front-service
spec:
  type: NodePort
  selector:
    app: prakash-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
